spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskList?currentSchema=taskList
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      #data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: Ym5zZGpnYm5haXFwQUtKSGdsa3NkZ2toQ3NidmRzanNramdWTg==
    access: 3600000
    refresh: 2592000000